[phases.setup]
nixPkgs = ["openjdk21", "maven"]

[phases.install]
cmds = ["mvn dependency:go-offline -B"]

[phases.build]
cmds = ["mvn clean package -DskipTests -B"]

[start]
cmd = "java -jar target/*.jar"
